Sdk basefiles
hyperledger-labs/avalon-sdk-py pull request #4
Opened 2020-10-12 11:51 UTC by karthikamurthy

Added interface folder from Github Avalon repo.
Repo: https://github.com/hyperledger/avalon.git
Folder path: avalon/sdk/avalon_sdk/connector/interfaces
Modified: No

2020-10-12 16:07 UTC, danintel requested changes
I see lookup tag spelled as `lookUpTag` or `lookupTag`. You should be consistent in the code (and also the comments) as this can be the cause of errors and bugs.

2020-10-13 07:18 UTC, karthikamurthy commented
> I see lookup tag spelled as `lookUpTag` or `lookupTag`. You should be consistent in the code (and also the comments) as this can be the cause of errors and bugs.

2020-10-13 07:19 UTC, Ram-srini approved these changes

2020-10-13 09:15 UTC, karthikamurthy commented
> I see lookup tag spelled as `lookUpTag` or `lookupTag`. You should be consistent in the code (and also the comments) as this can be the cause of errors and bugs.

Done

2020-10-14 15:02 UTC, danintel approved these changes

2020-10-15 04:46 UTC, merged